<?php 
    // Config plugins
    $labels_posts = array(
        'name' => _x('All Recipes Posts', 'Post type general name', 'textdomain'),
        'singular_name' => _x('Recipes posts', 'Post type singular name', 'textdomain'),
        'menu_name' => _x('Recipes posts', 'Admin Menu text', 'textdomain'),
        'name_admin_bar' => _x('Recipes posts', 'Add New on Toolbar', 'textdomain'),
        'add_new' => __('Add new posts recipes', 'textdomain'),
        'add_new_item' => __('Add new posts recipes', 'textdomain'),
        'new_item' => __('New posts recipes', 'textdomain'),
        'edit_item' => __('Edit posts recipes', 'textdomain'),
        'view_item' => __('View posts recipes', 'textdomain'),
        'all_items' => __('All posts recipes', 'textdomain'),
        'search_items' => __('Search posts recipes', 'textdomain'),
        'parent_item_colon' => __('Parent posts recipes:', 'textdomain'),
        'not_found' => __('Not content...', 'textdomain'),
        'not_found_in_trash' => __('Not found in Trash.', 'textdomain'),
        'featured_image' => _x('Image thumbnail', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3', 'textdomain'),
        'set_featured_image' => _x('Add thumbnail', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3', 'textdomain'),
        'remove_featured_image' => _x('Remove thumbnail', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3', 'textdomain'),
        'use_featured_image' => _x('Use as cover thumbnail', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3', 'textdomain'),
        'archives' => _x('Posts recipes archives', 'The post type archive label used in nav menus. Default “Post Archives”. Added in 4.4', 'textdomain'),
        'insert_into_item' => _x('Insert into posts recipes', 'Overrides the “Insert into post”/”Insert into page” phrase (used when inserting media into a post). Added in 4.4', 'textdomain'),
        'uploaded_to_this_item' => _x('Uploaded to this posts recipes', 'Overrides the “Uploaded to this post”/”Uploaded to this page” phrase (used when viewing media attached to a post). Added in 4.4', 'textdomain'),
        'filter_items_list' => _x('Filter posts recipes list', 'Screen reader text for the filter links heading on the post type listing screen. Default “Filter posts list”/”Filter pages list”. Added in 4.4', 'textdomain'),
        'items_list_navigation' => _x('Posts recipes list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Default “Posts list navigation”/”Pages list navigation”. Added in 4.4', 'textdomain'),
        'items_list' => _x('Posts recipes list', 'Screen reader text for the items list heading on the post type listing screen. Default “Posts list”/”Pages list”. Added in 4.4', 'textdomain'),
    );